# Generated by Django 4.0.2 on 2022-03-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='custumer',
        ),
    ]
